### ISSUE TITLE
Unauthenticated request

### ISSUE THREAD

**Issue by ts-sz** [EmbarkStudios/wireguard-ui#10] opened 2019-10-28 17:11 UTC
Hello,
ho I can use **authentication** for the welcome page ?
Thanks
![Capture d'écran Deepin_zone de sélection _20191028180935](https://user-images.githubusercontent.com/19378290/67700482-4d6b1580-f9ae-11e9-8efd-d258722ab067.png)
![Capture d'écran Deepin_zone de sélection _20191028180835](https://user-images.githubusercontent.com/19378290/67700486-4f34d900-f9ae-11e9-81ae-a75e49a0ac79.png)

**Comment by freddd** [comment] 2019-12-12 11:49
Hi @ts-sz and @jtc42,

Thank you for showing interest in the wireguard-ui. Once PR #19 gets merged we will be validating JWT's passed by from Googles IAP (https://cloud.google.com/iap/). I'm not sure if there are other cloud providers providing the same capabilities (but there are other auth proxies out there that might be of interest). Our current aim is to support validating JWT's from different providers with the help from the community, however we are starting with IAP. 

I will close the issue, feel free to open a new issue with the `enhancement` label if you have a feature request as this is not a bug.

**Closed by freddd** 2019-12-12 11:49 UTC
Labels: bug
