### ISSUE TITLE
Docker container not starting

### ISSUE THREAD

**Issue by engel75** [EmbarkStudios/wireguard-ui#11] opened 2019-10-30 15:27 UTC
**Describe the bug**
Following your instractions to test the UI stating the docker container fails with message:

Error: container_linux.go:346: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": OCI runtime command not found error

I tested with podman and docker-ce

**Comment by jtc42** [comment] 2019-11-03 17:13
I believe this is a duplicate of https://github.com/EmbarkStudios/wireguard-ui/issues/8

See https://github.com/EmbarkStudios/wireguard-ui/issues/8#issuecomment-544254043 for a possible solution

**Comment by suom1** [comment] 2019-11-22 17:35
We've updated the documentation with a working solution!

**Closed** 2019-11-22 17:35 UTC
Labels: bug
